# Generated by Django 5.2.12 on 2026-08-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('group', 'グループ'), ('room', 'トークルーム'), ('user', 'ユーザー')], default='group', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='linenotification',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='linenotify.linetarget'),
        ),
    ]
