# Generated by Django 5.2.12 on 2026-08-31 14:51
# 注: 画像添付機能は撤去済み（0004で削除）。参照していた upload_to 関数も
# models.py から消えたため、履歴ロード用に文字列へ差し替えている
# （upload_to はDBスキーマに影響しないので適用済み環境でも安全）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0002_linetarget_linenotification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='linenotification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='line/notification/'),
        ),
    ]
