# Generated by Django 5.2.12 on 2026-08-31 14:51

import linenotify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0002_linetarget_linenotification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='linenotification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=linenotify.models.notification_image_path),
        ),
    ]
