# Generated by Django 5.2.12 on 2026-08-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0003_linenotification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linenotification',
            name='image',
        ),
    ]
