# Generated by Django 5.2.12 on 2026-08-31 13:09

import django.db.models.deletion
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=todo.models.todo_attachment_path)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.todoitem')),
            ],
            options={
                'ordering': ['order', 'uploaded', 'id'],
            },
        ),
    ]
