# Generated by Django 5.2.12 on 2026-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['done', 'sort_order', '-importance', '-updated']},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
