# Generated by Django 5.2.12 on 2026-07-29 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('yellow', 'イエロー'), ('pink', 'ピンク'), ('green', 'グリーン'), ('blue', 'ブルー'), ('purple', 'パープル'), ('gray', 'グレー')], default='yellow', max_length=10)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', 'order', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('yellow', 'イエロー'), ('pink', 'ピンク'), ('green', 'グリーン'), ('blue', 'ブルー'), ('purple', 'パープル'), ('gray', 'グレー')], default='blue', max_length=10)),
                ('status', models.CharField(choices=[('todo', '未着手'), ('doing', '進行中'), ('done', '完了')], default='todo', max_length=8)),
                ('priority', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('reminded', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done_at', '-priority', 'due_at', 'created'],
            },
        ),
    ]
