# Generated by Django 5.2.12 on 2026-07-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
