# Generated by Django 5.2.12 on 2026-07-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusen', '0002_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
