# Generated by Django 5.2.12 on 2026-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusen', '0003_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
