# Generated by Django 5.2.12 on 2026-08-07 01:23

import django.db.models.deletion
import fusen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusen', '0004_note_time_task_all_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fusen.models.note_attachment_path)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fusen.note')),
            ],
            options={
                'ordering': ['uploaded', 'id'],
            },
        ),
    ]
