# Generated by Django 5.2.12 on 2026-08-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusen', '0005_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['order', 'uploaded', 'id']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
