# Generated by Django 5.2.12 on 2026-09-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('symbol', models.CharField(default='★', max_length=4, verbose_name='記号')),
                ('color', models.CharField(default='yellow', max_length=20, verbose_name='色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MailMarkAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns', to='mailfunction.mailmark')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mail_id', 'mark'), name='uniq_mail_mark')],
            },
        ),
    ]
