# Generated by Django 5.2.12 on 2026-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_index', models.IntegerField()),
                ('section_index', models.IntegerField()),
                ('day_index', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('公開FM', '公開FM'), ('有給', '有給'), ('公休', '公休'), ('本社', '本社'), ('公出勤', '公出勤'), ('', '未入力')], max_length=20)),
            ],
            options={
                'unique_together': {('sheet_index', 'section_index', 'day_index')},
            },
        ),
    ]
