# Generated by Django 5.2.12 on 2026-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workentry',
            name='person',
            field=models.CharField(choices=[('a', 'A氏'), ('b', 'B氏'), ('c', 'C氏'), ('d', 'D氏')], default='a', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together={('person', 'sheet_index', 'section_index', 'day_index')},
        ),
    ]
