# Generated by Django 5.2.12 on 2026-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0002_alter_workentry_unique_together_workentry_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('a', 'A氏'), ('b', 'B氏'), ('c', 'C氏'), ('d', 'D氏')], default='a', max_length=1)),
                ('sheet_index', models.IntegerField()),
                ('section_index', models.IntegerField()),
                ('day_index', models.IntegerField()),
                ('time_text', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'unique_together': {('person', 'sheet_index', 'section_index', 'day_index')},
            },
        ),
    ]
