# Generated by Django 5.2.12 on 2026-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0003_evententry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workentry',
            name='row_type',
            field=models.IntegerField(choices=[(0, '上番'), (1, '下番')], default=0),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='status',
            field=models.CharField(blank=True, choices=[('有給', '有給'), ('公休', '公休'), ('公出勤', '公出勤'), ('', '未入力')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together={('person', 'sheet_index', 'section_index', 'day_index', 'row_type')},
        ),
    ]
