# Generated by Django 5.2.12 on 2026-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0004_alter_workentry_unique_together_workentry_row_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='person',
            field=models.CharField(choices=[('a', 'A氏'), ('b', 'B氏'), ('c', 'C氏'), ('d', 'D氏'), ('e', 'E氏'), ('f', 'F氏'), ('g', 'G氏'), ('h', 'H氏'), ('i', 'I氏')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='person',
            field=models.CharField(choices=[('a', 'A氏'), ('b', 'B氏'), ('c', 'C氏'), ('d', 'D氏'), ('e', 'E氏'), ('f', 'F氏'), ('g', 'G氏'), ('h', 'H氏'), ('i', 'I氏')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
