# Generated by Django 5.2.12 on 2026-06-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0005_alter_evententry_person_alter_workentry_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('b', '竹田津'), ('c', '金山'), ('d', '三室'), ('e', '山田'), ('f', '芳松'), ('g', '表木'), ('h', '虎谷'), ('i', 'I氏')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('b', '竹田津'), ('c', '金山'), ('d', '三室'), ('e', '山田'), ('f', '芳松'), ('g', '表木'), ('h', '虎谷'), ('i', 'I氏')], default='a', max_length=1),
        ),
    ]
