# Generated by Django 5.2.12 on 2026-07-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0008_alter_evententry_person_alter_workentry_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('headers', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LayoutCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('text', models.CharField(blank=True, max_length=200)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='nitei.layoutday')),
            ],
            options={
                'ordering': ['race', 'col'],
                'unique_together': {('day', 'race', 'col')},
            },
        ),
        migrations.CreateModel(
            name='LayoutRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.PositiveSmallIntegerField()),
                ('start_time', models.CharField(blank=True, max_length=5)),
                ('close_time', models.CharField(blank=True, max_length=5)),
                ('highlight', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='nitei.layoutday')),
            ],
            options={
                'ordering': ['race'],
                'unique_together': {('day', 'race')},
            },
        ),
    ]
