# Generated by Django 5.2.12 on 2026-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0009_layoutday_layoutcell_layoutrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutcell',
            name='color',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
