# Generated by Django 5.2.12 on 2026-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0012_seed_layout_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('b', '竹田津'), ('c', '金山'), ('d', '三室'), ('e', '山田'), ('f', '芳松'), ('g', '表木'), ('h', '虎谷'), ('i', '栗原'), ('j', '小林'), ('k', 'S水'), ('l', 'I田'), ('m', '水野')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('b', '竹田津'), ('c', '金山'), ('d', '三室'), ('e', '山田'), ('f', '芳松'), ('g', '表木'), ('h', '虎谷'), ('i', '栗原'), ('j', '小林'), ('k', 'S水'), ('l', 'I田'), ('m', '水野')], default='a', max_length=1),
        ),
    ]
