# Generated by Django 5.2.12 on 2026-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitei', '0014_alter_evententry_person_alter_workentry_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('i', '栗原'), ('l', '生田'), ('k', '清水'), ('h', '虎谷'), ('j', '小林'), ('g', '表木'), ('c', '金山'), ('d', '三室'), ('m', '水野'), ('b', '竹田津'), ('e', '山田'), ('f', '芳松')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='person',
            field=models.CharField(choices=[('a', '松山'), ('i', '栗原'), ('l', '生田'), ('k', '清水'), ('h', '虎谷'), ('j', '小林'), ('g', '表木'), ('c', '金山'), ('d', '三室'), ('m', '水野'), ('b', '竹田津'), ('e', '山田'), ('f', '芳松')], default='a', max_length=1),
        ),
    ]
